name = "dogeub-deploystuffhjblhboljh" # Make sure this matches your project name in Cloudflare
compatibility_date = "2025-10-04"

# This is the correct way to specify a directory of static assets for a Worker
[assets]
directory = "./dist"
